# Generated by Django 6.0.4 on 2026-05-08 10:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', ckeditor.fields.RichTextField()),
                ('bullet_points', models.TextField(help_text='Enter each point in new line')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePageIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_content', ckeditor.fields.RichTextField()),
                ('center_image', models.ImageField(upload_to='services/intro/')),
                ('right_content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
