# Generated by Django 6.0.4 on 2026-05-08 18:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service_servicepageintro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('status', models.CharField(choices=[('history', 'Project History'), ('live', 'Live Projects'), ('upcoming', 'Upcoming Projects')], max_length=20)),
                ('project_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-project_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PROJECTS', max_length=200)),
                ('hero_image', models.ImageField(upload_to='projects/hero/')),
            ],
        ),
    ]
