# Generated by Django 6.0.4 on 2026-05-08 19:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_projectspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='social_services/')),
                ('status', models.CharField(choices=[('history', 'Service History'), ('ongoing', 'Ongoing Services'), ('upcoming', 'Upcoming Services')], max_length=20)),
                ('project_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-project_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOCIAL SERVICES', max_length=200)),
                ('hero_image', models.ImageField(upload_to='social_services/hero/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
